Initial commit, adding seeding input data cypress test
DickinsonCollege/FD2School-FarmData2 pull request #175
Opened 2023-03-30 21:29 UTC by Mikek16

__Pull Request Description__

<Add description>
Addresses #155 
---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

2023-04-05 15:54 UTC, braughtg requested changes
Please see the comments below for suggested revisions.

2023-04-05 15:54 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.data.defaults.spec.js
> +        // Cypress clears the local storage between each test.
These lines are not necessary in this test.

2023-04-05 15:54 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.data.defaults.spec.js
> +
Be sure to use consistent spacing.  On line between each `it` should be sufficent.

2023-04-05 15:54 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.data.defaults.spec.js
> +            .children()
It would be better to use the `data-cy` values for the options in the dropdown to check these values than to use the `children` function.

2023-04-05 22:17 UTC, Mikek16 commented
PR ready for review.

2023-04-06 12:07 UTC, braughtg requested changes

2023-04-06 12:07 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.data.defaults.spec.js
> +        cy.get("[data-cy=crop-selection] > [data-cy=dropdown-input]").should("have.text", "")
This line is not checking what you want it to.  It is checking that the entire text of the `dropdown-input` is `""`.  That will be true until the page retrieves the list of crops from the API and the computed property generates the crops that are passed to the `prop` of the `DropdownWithAllComonent`. 

To address this you'll need to check the value that is *selected* not the `text` of the element.  There is a question in the issue related to this.  @infantlikesprogramming should ask a followup there.

2023-04-11 19:46 UTC, braughtg approved these changes

2023-04-11 19:47 UTC, merged