Fix Issue #159 Test Seeding Input Direct Seeding Defaults
DickinsonCollege/FD2School-FarmData2 pull request #182
Opened 2023-04-04 01:49 UTC by won369369

__Pull Request Description__

Addressing #159 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

2023-04-12 15:55 UTC, braughtg requested changes

2023-04-12 15:55 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.type.defaults.spec.js
> +  it('test the first visit to the page (i.e. no cached crops and areas)', () => {
This test does not appear to address anything requested in the issue and should be removed.

2023-04-12 15:55 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.type.defaults.spec.js
> +  //issue 159 sub-task 1
These comments are fine during development for your reference, but should be removed when complete as they will not have immediate meaning to someone reading your code in the future.

2023-04-12 15:56 UTC, braughtg commented
Please review requested changes and mark the PR as ready for review again when they have been addressed.

2023-04-12 17:10 UTC, johnmaccormick commented
You have used some advanced Cypress techniques for managing the browser's local storage, if I understand correctly. All tests are passing, so that's great. But I would like to seek the opinion of a farmdata2 maintainer about whether it is a good idea to use these advanced techniques. I'm referring to the use of

* `localStorage.removeItem()`
* `cy.restoreLocalStorage()`
* `cy.saveLocalStorage()`
* `cy.intercept()`
* `cy.wait()`

I see that Prof Braught @braughtg  already made some similar comments above.

2023-04-12 17:10 UTC, johnmaccormick commented
I have another question about your advanced techniques. When checking the size of the list of areas, you compare it to the content of `JSON.parse(localStorage.getItem('areas'))`  -- but this raises an interesting question about testing technique. How do we know that the correct list was fetched and stored into the local storage? If we test that the fetched list has the same length as the drop-down list, have we covered the most likely type of errors intended to be covered by this test? I'm not sure of the answer, but I'm wondering if a simpler approach with a hardcoded length would be more robust. Interesting question for discussion.

2023-04-12 17:11 UTC, johnmaccormick commented
Overall, I think you've done good work on this issue and once the file name is correct there is a good chance it can be merged. Nice job!

2023-04-12 17:13 UTC, johnmaccormick reviewed
Overall, I think you've done good work on this issue and once the file name is correct there is a good chance it can be merged. Nice job!

2023-04-16 16:31 UTC, braughtg requested changes

2023-04-16 16:31 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.direct.defaults.spec.js
> +      .then(() => {
The assertions here should not be enclosed in a `then()`.  When inclosed in a `then()` they are executed asynchronously and this test method may exit before they execute.  This can result in any `afterEach` clause executing before the assertions.  While you do not have an `afterEach()` here, and this will likely work just fine, it is better to maintain consistency across tests by not enclosing the `should()` statements in `then()` clauses.

Note this also applies to an additional test above.

2023-04-16 16:31 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.direct.defaults.spec.js
> +  it('test if areas are correctly loaded to the dropdown for direct seeding', () => {
Because the test is checking the areas, which are loaded by an API call in the page, it would be good to add a call to `cy.waitForPage()` to the start of this test.  That function call will cause the test to pause and wait for the entire page to be loaded, which will ensure that the area dropdown has been populated before the rest of the test runs.

This test should also check that the area dropdown is enabled.  See sub-task #2.

2023-04-16 16:33 UTC, braughtg commented
Overall these tests are pretty good.  To be eventually be merged into the upstream there are additional issues described above that should be addressed.  Please ask here if you have questions about the requested changes.

2023-04-20 02:24 UTC, johnmaccormick commented
Hi, I still don't see where the test checks that the area dropdown is enabled. This is subtask number 2. Am I missing something? Let me know if so, if not, please add the explicit test that checks the area dropdown is enabled. 

One more thing: As we discussed, Professor Braught asked you to remove the comments indicating the subtask numbers... But I asked you to leave them since it makes it easier for me to review. When I do merge your PR, I will manually delete these comments. To do that, I need to have write permission on your repo and also you should check the settings on your PR to make sure that maintainers can make edits. Let's see if we can get that part of the workflow operating correctly – it would be an interesting experiment. If it causes problems, I will just ask you to delete those comments yourself, but I think there is a good use case for the maintainer making some minor final tweaks before merging, as described on [StackOverflow](https://stackoverflow.com/questions/73259187/received-a-pull-request-from-someone-else-how-to-edit-it-before-merging-directl)

2023-04-21 03:50 UTC, won369369 commented
Dear Professor @johnmaccormick, 
1. We implemented the test checks that the area dropdown is enabled. 
2. What I learned from Oppia is that the blue checkbox must be visible on the PR website for maintainers to make changes to contributors' code. I don't see it from my current point of view.
![image](https://user-images.githubusercontent.com/60108250/233536445-6a8b7dec-870f-43d9-bc6b-a0abb52317b2.png)

2023-04-21 13:42 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.direct.defaults.spec.js
> +  it('test if areas are correctly loaded to the dropdown for direct seeding', () => {
@won369369 @Shahir-47 @JinLeeGG  -- It looks like you still need to follow up on the suggestion to add a `cy.waitForPage()`

2023-04-21 13:46 UTC, johnmaccormick commented
Okay, it looks like I still don't have write permission on your repo, but I'm happy to abandon that experiment. I see you have deleted the comments that help me identify the subtasks already. So, this file is nearly ready to be merged. My only remaining request is that you add a general comment at the top of the file describing in plain English what the purpose of the file is. (And also see my more detailed comment in the *Files changed* tab -- do you need to add `cy.waitForPage()`?)

2023-04-21 15:26 UTC, braughtg commented
When the above 2 changes are addressed this will be ready for merge into the upstream.
  * Add `cy.waitForPage()`
  * Remove the sub-task comments after Prof. MacCormick confirms he no longer needs them.

2023-04-21 20:11 UTC, johnmaccormick commented
@won369369 @JinLeeGG @Shahir-47 -- One last thing. Please add a comment at the top of the file describing what the purpose of the file is. After that, upgrade from draft to regular pull request and I think it will be ready to be merged!

2023-04-24 22:57 UTC, merged

2023-04-24 22:58 UTC, johnmaccormick commented
nice job -- successfully merged