Tray feature
DickinsonCollege/FD2School-FarmData2 pull request #194
Opened 2023-04-05 15:47 UTC by qnhn22

__Pull Request Description__

We wrote tests for the Tray Seeding section of the Seeding Input Form.
Addresses #158 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

2023-04-07 20:09 UTC, johnmaccormick commented
Hi, I'm seeing the following error when running your tests:

![image](https://user-images.githubusercontent.com/1777822/230672048-29d6f0c9-0cd3-481d-b893-bbaa3c92975a.png)

Is that actually an error in my testing infrastructure or is this a problem with your test? Please comment below and I will take another look at it.

Meanwhile, there are a couple of other elementary improvements required for your code. Some of the indentation is not correct and there are some blank lines in places where it is unnecessary or visually unappealing. Please try to fix the layout of your code to conform to standard conventions.

Nice job on implementing the majority of these tests.

2023-04-07 20:18 UTC, johnmaccormick requested changes
I'm just learning the GitHub reviewing workflow. This comment is part of a "review" of your PR. Please see my earlier comment for suggested changes.

2023-04-08 15:53 UTC, braughtg requested changes
Please see the comments on this PR below.

2023-04-08 15:53 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +    cy.get("[data-cy=num-cell-input] > [data-cy=text-input]")
This test does not need to check that values can be entered into the fields.  That will be accomplished by a separate test that checks the behavior of the form.  Similar comments apply elsewhere in this file.

2023-04-08 15:53 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +
This test should also check that no area is selected by default.

2023-04-08 15:53 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +                                    .children().should("be.empty")
I don't think that checking that `children().should("be.empty")` is testing what you intend.  That check that this element does not have any children.  Not that this text field is empty.  For that you need to check its value with `has.value`.

2023-04-09 15:09 UTC, johnmaccormick commented
Following up on my earlier comment about the test failing, I do now see that it passes sometimes when I run it. I'm not sure if it is essential to find out why this test sometimes fails. Perhaps we can investigate this further with Professor Braught. I wonder if there is a way we can prevent the test from timing out. We would want to verify whether or not this type of nondeterministic failure of the test is acceptable for merging into the ultimate upstream repo of FD2.

2023-04-09 15:37 UTC, johnmaccormick commented
in the [original issue](https://github.com/DickinsonCollege/FD2School-FarmData2/issues/158), there is a requirement to check that "the four greenhouses and seeding bench in the sample data are in the dropdown." Is it suficient to check that there are 5 elements? Or are more detailed checks of the content required? Please ask a question to the maintainer who posted the issue to find out what type of test is required here.

2023-04-09 15:41 UTC, johnmaccormick commented
I think I see one problem which may be the cause of your tests sometimes failing. The first two it() methods are inside the describe(), but the rest of them are outside the describe(). I suspect this causes various problems, including the fact that the beforeEach() is probably not being run separately for the it() methods outside the describe().

2023-04-09 15:54 UTC, johnmaccormick commented
The issue states "The .spec.js file should include a comment at the top that describes what the file as a whole is testing." -- but I don't see a comment at the top

2023-04-12 03:34 UTC, qnhn22 commented
> Following up on my earlier comment about the test failing, I do now see that it passes sometimes when I run it. I'm not sure if it is essential to find out why this test sometimes fails. Perhaps we can investigate this further with Professor Braught. I wonder if there is a way we can prevent the test from timing out. We would want to verify whether or not this type of nondeterministic failure of the test is acceptable for merging into the ultimate upstream repo of FD2.

Hi Professor MacCormick,
The test that you mentioned works perfectly on my machine.The error occurred in your testing infrastructure possibly because it might take longer time to run compared to other tests. Thank you for your review.

2023-04-12 13:09 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +        cy.get("[data-cy=tray-area-selection]>[data-cy=dropdown-input]").should("have.text","")
This does not actually test if the selected value in the dropdown is empty.  It is checking that the entire dropdown has no text (i.e. no options at all).  This passes because that dropdown is populated from an API call in the `created` hook.  To see this add a call to `cy.waitForPage()` to the top of this test.  That will cause the test to wait until the API calls are complete.  Then this test should fail because the dropdown will have options.  

To fix this, you'll then need to check the value of the dropdown, not its text.

2023-04-12 13:12 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +                                        .children().should("have.value","")
I am not sure what checking that `children()` have the value `""` is doing here.  `children()` gives a list of the elements that are children of the `tray-input`.   I think you just want to check the value that is in the field itself.  Have a look at the documentation for the component being used and find the `data-cy` for the element that you want to test and use it.

2023-04-12 15:42 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +
Please remove excess blank lines.  A single line between logically distinct sections of code is still appropriate.

2023-04-12 15:45 UTC, braughtg commented
> The test that you mentioned works perfectly on my machine.

The tests in the `seedingInput.tray.defaults.spec.js` run reliably on my machine.  

Please address the changes requested in the review and mark as ready for review again when complete.

2023-04-20 03:17 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +        cy.get("[data-cy=tray-area-selection]>[data-cy=dropdown-input]").should("be.visible")
The Issue requires that we check the drop-down is enabled. Is this the same thing as being visible? Would it be a more accurate implementation of the Issue to verify that the drop-down is enabled rather than visible?

2023-04-20 03:18 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +    it("Check the tray seeding section when 'Tray' is selected ", () => {
This is a really minor point, but... High-quality code should use consistent line spacing conventions. There is a blank line before every other `it()`, so there should be a blank line before this one also.

2023-05-03 17:43 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingReport.spec.js
thanks for fixing!

2023-05-03 17:56 UTC, qnhn22 commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +    cy.get("[data-cy=num-cell-input] > [data-cy=text-input]")
This problem is resolved.

2023-05-03 17:56 UTC, nguyenbanhducA1K51 commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +                                    .children().should("be.empty")
This will be fixed in the next commit

2023-05-03 18:21 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +        cy.get("[data-cy=tray-area-selection]>[data-cy=dropdown-input]").should("be.visible")
Please can you also test that the dropdown should("be.enabled")

2023-05-03 18:21 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.tray.defaults.spec.js
> +    it("Check the tray seeding section when 'Tray' is selected ", () => {
please add the blank line as mentioned above. Thanks!

2023-05-03 18:44 UTC, johnmaccormick commented
Thanks for the latest fixes -- this is being merged now!

2023-05-03 18:44 UTC, merged