Added new test file with before each
DickinsonCollege/FD2School-FarmData2 pull request #196
Opened 2023-04-08 00:07 UTC by Alexandrialexie

__Pull Request Description__

Closes #187 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

2023-04-08 15:41 UTC, braughtg commented
Please update the title of this PR to be descriptive of what it is addressing and also provide some additional descriptive content in the body text of the PR. That will help the project maintainers better understand what you are working on.  Thanks!

2023-04-12 22:26 UTC, pranavm2109 commented
Hi professor, quick question.
I have been trying to test the presence of logs pertaining to the crop CAULIFLOWER in cypress. However, when I am invoking the have.value command to compare it with the expected value (that is 'CAULIFLOWER'), I am getting an AssertionError, stating that the value retrieved was 'CAULIFLOWER                ' and not 'CAULIFLOWER'. Why is this the case? Why are there extra spaces at the end of the value retrieved from the table? Can I call a trim method (if it exists) to remove these trailing whitespaces?

2023-04-12 23:12 UTC, braughtg commented
> I am getting an AssertionError, stating that the value retrieved was 'CAULIFLOWER ' and not 'CAULIFLOWER'. Why is this the case?

It does seem like that extra space should not be there.  It must be getting added in somewhere along the line.  It could be in the database that way, it could that the Seeding Report is adding a space in the `computed` property that is generating the rows for the table, or it could be that the `CustomTableComponent` is adding a space when it is put into the `<td>` element.

I would suggest the following.  Use the `contain.text` assertion in your test as that works sufficiently well.  However, as you note it would be better to be able to use `has.text`.  So please also create a new issue in the issue tracker describing the problem in sufficient detail that someone will be able to diagnose it.  You should reference your PR in that issue and indicate how your test should change once the issue is resolved.

Then if there is interest, this would be a great thing for your team to investigate and try to resolve.

2023-04-16 16:48 UTC, braughtg requested changes
Overall these are nice looking tests!  There are just a few requested changes that will get them to where they can be merged into the upstream FarmData2.

2023-04-16 16:48 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.crop.filter.spec.js
> +            .children()
In general, if an element provides a `data-cy` attribute that should be used instead of `children()`.  Here the `DropdownWithAllComponent` defines `data-cy` attributes with the value `optionX` for each option `X`.

Note that using `children()` is the correct approach for checking the `length`.

2023-04-16 16:48 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.crop.filter.spec.js
> +
Please remove excess blank lines.

2023-04-16 16:48 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.crop.filter.spec.js
> +        //Check date range 07/06/2019 - 07/12/2019
This comment does not seem to add useful information and should be removed.  The following lines make it clear which date range is being used.

Similarly, please review comments below to determine if they add information beyond what is in the associated line of code.  If a reasonably skilled developer (e.g. someone with similar training to yourselves) can readily discern the information in the comment from the code, then the comment can be omitted.

2023-04-16 16:48 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.crop.filter.spec.js
> +        //make a list of the crops expected in the list
This is an effective and clever way to do this test!  Nicely done!!

This is one place where a comment would be really helpful!  Maybe remove the individual line comments and add a comment here describing your overall approach to testing that the table only contains valid crops.

2023-04-16 16:48 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.crop.filter.spec.js
> +
Remove excess blank lines here.

2023-05-09 13:24 UTC, braughtg commented
Nicely done!

2023-05-09 13:24 UTC, merged