Fix issue 186
DickinsonCollege/FD2School-FarmData2 pull request #210
Opened 2023-04-12 17:57 UTC by Mikek16

__Pull Request Description__

<Add description>
Addresses #186 
---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

2023-04-19 16:45 UTC, braughtg requested changes
You seem to have multiple different approaches to performing the same types of tests within this file.  Some use the `expectedHeaderNames`, others simply use one line for each header, and others use the `allHeaders` variable.  It would be better to standardize the way you are performing the tests so that once a reader figures out what you are doing in one place they will find it easier to follow the other places.

Another recommendation would be to keep things as simple as possible in the tests.  Only make tests do more complicated computation when it provides a significant advantage over simpler but equally effective approaches.  When you do opt for something more complex, then a comment explaining the approach will be helpful to the reader.

2023-04-19 16:45 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +        cy.waitForPage()
This line will not have any effect here.  The page has already loaded when the `cy.waitForPage()` you have earlier has completed.

2023-04-19 16:45 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +      cy.scrollTo(0,50)
It should not be necessary to scroll here.  The elements only need to actually be in view if you are using an action (e.g. `click()` on them) and Cypress should automatically scroll them into view when you use `cy.get()`.

2023-04-19 16:45 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +      cy.get(" [data-cy=table-headers]").children().eq(1).should('have.text',"Date")
There is a `data-cy` attribute for each table header.  It would be preferable to use those rather than `children().eq(...)` to get the header that you want to test.  In general, if there is a `data-cy` attribute available it should be used rather than any other approach. It will make your tests more robust with respect to changes in the page or components.

2023-04-19 16:45 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +      cy.wait(1000)
You should not need to use `cy.wait()`.  Cypress will automatically retry the `cy.get(...)` commands for up to 10 seconds.

2023-05-03 16:45 UTC, Mikek16 commented
This pull request is ready for review

2023-05-09 13:42 UTC, braughtg requested changes
These tests look pretty good.  It is not necessary for the course, but if you would like this PR to be merged, please address the comments in this review and mark it as read for review again.  I will leave this open through the end of May.

2023-05-09 13:42 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +        if(includedHeaders.includes(header.header)){
With this approach, it seems like you should also have an `else` clause that checks that the headers that are not supposed to be there are not visible.

2023-05-09 13:42 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +      //Check the User header seperately
I see you checked `User` separately in each test.  It doesn't seem like that should be necessary.  Is there a reason that it was done this way?

2023-05-13 06:22 UTC, Mikek16 commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +        if(includedHeaders.includes(header.header)){
This has been included

2023-05-13 06:24 UTC, Mikek16 commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +      //Check the User header seperately
using  .should('be.visible') to check for the User head would result in the following error:
"This element <th> is not visible because it has CSS property: position: fixed and it's being covered by another element
<section class="col-sm-12">...</section> "
to address this, the tests now use .should('exist') to check for headers.

2023-05-14 13:17 UTC, braughtg requested changes
Really nice work revising this PR!  You found a nice effective and efficient way to do the testing.  Just a few small changes and its good to go!

2023-05-14 13:17 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +    cy.get('[data-cy=report-table]')
This check should come before the two above for the checkboxes.  If the table does not exist then those will fail, so if the test gets here it will always pass. If you move it before the others, then it is a good thing to include as it would provide different information about what is wrong.

2023-05-14 13:17 UTC, braughtg commented on farmdata2/farmdata2_modules/fd2_barn_kit/seedingReport/seedingReport.columns.spec.js
> +    cy.get('[data-cy=selectAll-checkbox]').should('be.visible');
The first test checks `not.be.disabled` here as well.  That seems like a good test to include in all three `it`.

2023-05-15 17:58 UTC, braughtg commented
Well done!!

2023-05-15 17:58 UTC, merged