Create test file for the Seeding Input
DickinsonCollege/FD2School-FarmData2 pull request #211
Opened 2023-04-12 18:45 UTC by jamesng5

__Pull Request Description__

Create new test file for SeedingInput #160 

---
__Licensing Certification__

FarmData2 is a [Free Cultural Work](https://freedomdefined.org/Definition) and all accepted contributions are licensed as described in the LICENSE.md file. This requires that the contributor holds the rights to do so. By submitting this pull request __I certify that I satisfy the terms of the [Developer Certificate of Origin](https://developercertificate.org/)__ for its contents.

2023-04-20 19:59 UTC, johnmaccormick requested changes
nice! -- minor suggestions for changes

2023-04-20 19:59 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html
> +        <h1 data-cy="header" style='text-align:center;'>Seeding Input Log</h1>
Would  more unique name be better here?

2023-04-20 19:59 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.misc.defaults.spec.js
> +    it('Test the comment text box is empty and enable', ()=>{
typo -- "enabled"

2023-04-20 19:59 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.misc.defaults.spec.js
> +    it("Check that the section has a label comment", () => {
use consistent line spacing

2023-04-20 20:01 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.misc.defaults.spec.js
> +})
have you checked that the label is "Comments"?

2023-04-21 20:04 UTC, johnmaccormick commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.misc.defaults.spec.js
> +})
Just clarifying, note that one of the tasks in Issue #160 is: 'has a section with the label "Comments"' -- so you should really check the label itself not just the visibility.

2023-04-24 03:06 UTC, jamesng5 commented on farmdata2/farmdata2_modules/fd2_field_kit/seedingInput/seedingInput.html
> +        <h1 data-cy="header" style='text-align:center;'>Seeding Input Log</h1>
This name is from the original file, and we did not add or make any changes in seedingInput.html file.

2023-04-25 00:13 UTC, johnmaccormick commented
@jamesng5 @vuphuongha @tainguyen103 -- The final test is failing. See if you find the problem on your own. If not, let me know and I will give you a hint. 

Other things to work on:
* make sure you have consistent spacing between the it() blocks
* put a comment at the top of the file explaining the purpose of this file

2023-04-25 00:29 UTC, tainguyen103 commented
@johnmaccormick Professor MacCormick, are you referring to the "Check that the submit button is disabled"? I tried running the test on my machine and it works fine. 

<img width="1023" alt="Screenshot 2023-04-24 at 8 27 17 PM" src="https://user-images.githubusercontent.com/108405800/234145349-3e531ff8-a60b-478e-95de-e5fe6f66d7be.png">

2023-04-26 01:55 UTC, jamesng5 commented
> @jamesng5 @vuphuongha @tainguyen103 -- The final test is failing. See if you find the problem on your own. If not, let me know and I will give you a hint.
> 
> Other things to work on:
> 
> * make sure you have consistent spacing between the it() blocks
> * put a comment at the top of the file explaining the purpose of this file

I have done working on this. Please let me know if any further changes needed.

2023-04-27 22:16 UTC, johnmaccormick commented
@tainguyen103 @vuphuongha @jamesng5  --

The final test that looks for the "Comment" is still failing for me. Here is what I see:

![image](https://user-images.githubusercontent.com/1777822/235002678-02206954-bfc8-4174-8da1-c697c5bdb6f9.png)

can you confirm that this test is *not* failing for you?

2023-04-27 23:54 UTC, vuphuongha commented
<img width="1011" alt="Screenshot 2023-04-27 at 7 52 16 PM" src="https://user-images.githubusercontent.com/60118892/235014111-f5d5fc93-2e3c-46a9-8a41-a9626fc54121.png">
Not sure what happened, but it worked fine on my end. Should I check with you again during tomorrow's office hours? @johnmaccormick

2023-04-28 11:32 UTC, braughtg commented
> The final test that looks for the "Comment" is still failing for me.

I see this test as failing on my system as well.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/16962482/235136799-04e7d5ce-9e4e-485d-b517-4e07c729b4e4.png">

2023-05-03 18:06 UTC, johnmaccormick commented
nice work, this is now being merged!

2023-05-03 18:06 UTC, merged